begin;

create extension if not exists pgcrypto;

create table organizations (id text primary key, name text not null check(length(trim(name)) between 1 and 160), timezone text not null default 'Asia/Makassar', settings_json jsonb not null default '{}'::jsonb, version integer not null default 1 check(version>0), created_at text not null, updated_at text not null);
create table users (id text primary key, organization_id text not null references organizations(id), email text not null, display_name text not null, status text not null default 'inactive' check(status in ('active','inactive','suspended')), last_login_at text, version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, unique(organization_id,email), unique(organization_id,id));
create unique index users_org_email_ci on users(organization_id,lower(email));
create table roles (id text primary key, code text not null unique check(code in ('super_admin','admin','worship_coordinator','field_coordinator','servant','public_viewer')), name text not null, system_managed integer not null default 1 check(system_managed=1));
create table permissions (id text primary key, code text not null unique, description text not null);
create table role_permissions (role_id text not null references roles(id), permission_id text not null references permissions(id), primary key(role_id,permission_id));
create table user_roles (id text primary key, organization_id text not null references organizations(id), user_id text not null, role_id text not null references roles(id), granted_by text not null, granted_at text not null, revoked_at text, version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, foreign key(organization_id,user_id) references users(organization_id,id), foreign key(organization_id,granted_by) references users(organization_id,id));
create unique index user_roles_active on user_roles(organization_id,user_id,role_id) where revoked_at is null;
create table coordinator_scopes (id text primary key, organization_id text not null references organizations(id), user_id text not null, scope_type text not null check(scope_type in ('service','field')), scope_id text not null, starts_at text not null, ends_at text check(ends_at is null or ends_at>starts_at), version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, foreign key(organization_id,user_id) references users(organization_id,id));
create index scopes_actor on coordinator_scopes(organization_id,user_id,scope_type,scope_id);
create table audit_logs (id text primary key, organization_id text not null references organizations(id), actor_type text not null check(actor_type in ('user','system')), actor_id text, action text not null, entity_type text not null, entity_id text not null, request_id text not null, metadata_redacted_json jsonb not null default '{}'::jsonb, created_at text not null, foreign key(organization_id,actor_id) references users(organization_id,id));
create index audit_org_time on audit_logs(organization_id,created_at,id);

create table role_changes (id text primary key, organization_id text not null references organizations(id), actor_id text not null, user_id text not null, idempotency_key text not null, roles_json jsonb not null, expected_version integer not null, actual_version integer not null, actor_authorized boolean not null constraint role_actor_authorized check(actor_authorized), target_exists boolean not null constraint role_target_exists check(target_exists), preserves_admin boolean not null constraint role_preserves_admin check(preserves_admin), created_at text not null, constraint role_version_matches check(expected_version=actual_version), unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,user_id) references users(organization_id,id));
create table user_creations (id text primary key, organization_id text not null references organizations(id), actor_id text not null, user_id text not null, idempotency_key text not null, payload_hash text not null check(length(payload_hash)=64), actor_authorized boolean not null constraint creation_actor_authorized check(actor_authorized), created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,user_id) references users(organization_id,id) deferrable initially deferred);
create table account_status_changes (id text primary key, organization_id text not null references organizations(id), actor_id text not null, user_id text not null, idempotency_key text not null, requested_status text not null check(requested_status in ('active','inactive','suspended')), expected_version integer not null, actual_version integer not null, actor_authorized boolean not null constraint status_actor_authorized check(actor_authorized), target_exists boolean not null constraint status_target_exists check(target_exists), preserves_admin boolean not null constraint status_preserves_admin check(preserves_admin), created_at text not null, constraint status_version_matches check(expected_version=actual_version), unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,user_id) references users(organization_id,id));
create index role_changes_org_retention on role_changes(organization_id,created_at);
create index user_creations_org_retention on user_creations(organization_id,created_at);
create index account_status_changes_org_retention on account_status_changes(organization_id,created_at);
create table bootstrap_state (singleton integer primary key check(singleton=1), organization_id text not null unique references organizations(id) deferrable initially deferred, payload_hash text not null check(length(payload_hash)=64), initialized_at text not null);
create table audit_retention_holds (audit_log_id text primary key references audit_logs(id), organization_id text not null references organizations(id), reason text not null check(length(trim(reason)) between 1 and 500), decision_owner text not null check(length(trim(decision_owner)) between 1 and 120), review_at text not null, created_at text not null, updated_at text not null);

create table service_fields (id text primary key, organization_id text not null references organizations(id), code text not null check(length(code) between 1 and 64), name text not null check(length(trim(name)) between 1 and 120), active integer not null default 1 check(active in (0,1)), version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, unique(organization_id,code), unique(organization_id,id));
create table service_roles (id text primary key, organization_id text not null references organizations(id), field_id text not null, code text not null check(length(code) between 1 and 64), name text not null check(length(trim(name)) between 1 and 120), slots_required integer not null default 1 check(slots_required between 1 and 99), active integer not null default 1 check(active in (0,1)), criticality text not null default 'normal' check(criticality in ('normal','critical')), version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, foreign key(organization_id,field_id) references service_fields(organization_id,id), unique(organization_id,code), unique(organization_id,id));
create table servants (id text primary key, organization_id text not null references organizations(id), user_id text, display_name text not null check(length(trim(display_name)) between 1 and 120), status text not null default 'active' check(status in ('active','inactive','pending_review')), telegram_chat_id text, telegram_user_id text, is_backup integer not null default 0 check(is_backup in (0,1)), administrative_note text, version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, foreign key(organization_id,user_id) references users(organization_id,id), unique(organization_id,id), unique(organization_id,user_id), unique(organization_id,telegram_chat_id));
create unique index servants_telegram_user_unique on servants(organization_id,telegram_user_id) where telegram_user_id is not null;
create table servant_capabilities (id text primary key, organization_id text not null references organizations(id), servant_id text not null, service_role_id text not null, status text not null default 'active' check(status in ('active','inactive','pending_approval')), approved_by text, approved_at text, monthly_assignment_limit integer check(monthly_assignment_limit between 1 and 99), version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, foreign key(organization_id,servant_id) references servants(organization_id,id), foreign key(organization_id,service_role_id) references service_roles(organization_id,id), foreign key(organization_id,approved_by) references users(organization_id,id), check((status='active' and approved_by is not null and approved_at is not null) or status<>'active'), unique(organization_id,servant_id,service_role_id));
create table capability_approvers (id text primary key, organization_id text not null references organizations(id), service_role_id text not null, user_id text not null, active integer not null default 1 check(active in (0,1)), created_at text not null, updated_at text not null, foreign key(organization_id,service_role_id) references service_roles(organization_id,id), foreign key(organization_id,user_id) references users(organization_id,id), unique(organization_id,service_role_id,user_id));
create table availability_blocks (id text primary key, organization_id text not null references organizations(id), servant_id text not null, starts_at text not null, ends_at text not null check(ends_at>starts_at), block_type text not null default 'unavailable' check(block_type in ('unavailable','preference')), note_private text, version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, foreign key(organization_id,servant_id) references servants(organization_id,id), unique(organization_id,id));
create table worship_services (id text primary key, organization_id text not null references organizations(id), starts_at text not null, assembly_at text not null check(assembly_at<=starts_at), ends_at text not null check(ends_at>starts_at), location text not null check(length(trim(location)) between 1 and 160), status text not null default 'draft' check(status in ('draft','scheduled','completed','postponed','cancelled')), theme text, notes text, cancellation_reason text, title text, published_at text, rescheduled_from_json jsonb, version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, check(status<>'cancelled' or cancellation_reason is not null), unique(organization_id,id));
create table assignments (id text primary key, organization_id text not null references organizations(id), worship_service_id text not null, service_role_id text not null, servant_id text not null, status text not null default 'draft' check(status in ('draft','awaiting_confirmation','accepted','unavailable','needs_replacement','reassigned','absent','completed','cancelled')), slot_number integer not null default 1 check(slot_number between 1 and 99), confirmed_at text, source_import_row_id text, version integer not null default 1 check(version>0), created_at text not null, updated_at text not null, foreign key(organization_id,worship_service_id) references worship_services(organization_id,id), foreign key(organization_id,service_role_id) references service_roles(organization_id,id), foreign key(organization_id,servant_id) references servants(organization_id,id), unique(organization_id,id));
create unique index assignments_active_slot_number on assignments(organization_id,worship_service_id,service_role_id,slot_number) where status not in ('cancelled','reassigned');
create index services_org_time on worship_services(organization_id,starts_at,id);
create index assignments_org_servant_status on assignments(organization_id,servant_id,status,id);
create index availability_org_servant_time on availability_blocks(organization_id,servant_id,starts_at,ends_at);

create table worship_service_creations (id text primary key, organization_id text not null, actor_id text not null, worship_service_id text not null, idempotency_key text not null, payload_hash text not null check(length(payload_hash)=64), actor_authorized boolean not null constraint service_creation_actor_authorized check(actor_authorized), created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,worship_service_id) references worship_services(organization_id,id) deferrable initially deferred);
create table worship_service_status_changes (id text primary key, organization_id text not null, actor_id text not null, worship_service_id text not null, idempotency_key text not null, requested_status text not null, expected_version integer not null, actual_version integer not null, actor_authorized boolean not null constraint service_status_actor_authorized check(actor_authorized), target_exists boolean not null constraint service_status_target_exists check(target_exists), created_at text not null, constraint service_status_version_matches check(expected_version=actual_version), unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,worship_service_id) references worship_services(organization_id,id));
create table assignment_creations (id text primary key, organization_id text not null, actor_id text not null, assignment_id text not null, idempotency_key text not null, payload_hash text not null check(length(payload_hash)=64), actor_authorized boolean not null constraint assignment_creation_actor_authorized check(actor_authorized), created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,assignment_id) references assignments(organization_id,id) deferrable initially deferred);
create table assignment_status_changes (id text primary key, organization_id text not null, actor_id text not null, assignment_id text not null, idempotency_key text not null, requested_status text not null, expected_version integer not null, actual_version integer not null, actor_authorized boolean not null constraint assignment_status_actor_authorized check(actor_authorized), target_exists boolean not null constraint assignment_status_target_exists check(target_exists), created_at text not null, constraint assignment_status_version_matches check(expected_version=actual_version), unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,assignment_id) references assignments(organization_id,id));
create table operational_mutation_receipts (id text primary key, organization_id text not null, actor_id text not null, idempotency_key text not null, action text not null, entity_id text not null, payload_hash text not null check(length(payload_hash)=64), actor_authorized boolean not null constraint operational_actor_authorized check(actor_authorized), created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id));

create table import_batches (id text primary key, organization_id text not null references organizations(id), uploaded_by text not null, original_filename text not null check(length(original_filename)<=180), checksum text not null check(length(checksum)=64), sheet_name text, mapping_json jsonb not null default '{}'::jsonb, date_format text check(date_format in ('dmy','mdy')), timezone text not null default 'Asia/Makassar', status text not null check(status in ('uploaded','validating','needs_review','ready','committing','committed','failed','rolled_back','expired')), expires_at text not null, committed_at text, version integer not null default 1, created_at text not null, updated_at text not null, foreign key(organization_id,uploaded_by) references users(organization_id,id), unique(organization_id,id));
create table import_rows (id text primary key, batch_id text not null references import_batches(id), organization_id text not null, row_number integer not null check(row_number between 1 and 5001), source_number text, raw_json jsonb not null, normalized_json jsonb not null, status text not null check(status in ('valid','warning','error','excluded','committed','skipped')), proposed_action text not null check(proposed_action in ('create','skip','merge_assignments','create_separate')), error_codes_json jsonb not null default '[]'::jsonb, warning_codes_json jsonb not null default '[]'::jsonb, override_starts_at text, warnings_acknowledged_at text, duplicate_service_id text, created_at text not null, updated_at text not null, unique(batch_id,row_number), unique(organization_id,id), foreign key(organization_id,batch_id) references import_batches(organization_id,id));
alter table assignments add foreign key(source_import_row_id) references import_rows(id);
create table import_resolutions (id text primary key, organization_id text not null, import_row_id text not null, field_name text not null check(field_name in ('preacher','mc','offering','location','duplicate')), resolution_type text not null check(resolution_type in ('link_existing','create_pending_review','exclude','skip','merge_assignments','create_separate')), target_entity_id text, resolved_by text not null, created_at text not null, foreign key(organization_id,import_row_id) references import_rows(organization_id,id), foreign key(organization_id,resolved_by) references users(organization_id,id), unique(import_row_id,field_name));
create table import_results (id text primary key, organization_id text not null, import_row_id text not null, entity_type text not null, entity_id text not null, action text not null check(action in ('created','skipped','merged','voided')), rollback_status text not null default 'available' check(rollback_status in ('available','voided','blocked')), created_at text not null, foreign key(organization_id,import_row_id) references import_rows(organization_id,id), unique(import_row_id,entity_type,entity_id));
create table import_commit_receipts (id text primary key, organization_id text not null, actor_id text not null, batch_id text not null, idempotency_key text not null, payload_hash text not null check(length(payload_hash)=64), created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,batch_id) references import_batches(organization_id,id));
create table import_resolution_receipts (id text primary key, organization_id text not null, actor_id text not null, import_row_id text not null, idempotency_key text not null, action text not null check(action='exclude'), created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,import_row_id) references import_rows(organization_id,id));
create table import_rollback_receipts (id text primary key, organization_id text not null, actor_id text not null, batch_id text not null, idempotency_key text not null, created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,batch_id) references import_batches(organization_id,id));
create table import_link_receipts (id text primary key, organization_id text not null, actor_id text not null, import_row_id text not null, field_name text not null check(field_name in ('preacher','mc')), target_servant_id text not null, idempotency_key text not null, created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,import_row_id) references import_rows(organization_id,id), foreign key(organization_id,target_servant_id) references servants(organization_id,id));
create table import_pending_receipts (id text primary key, organization_id text not null, actor_id text not null, import_row_id text not null, field_name text not null check(field_name in ('preacher','mc')), servant_id text not null, idempotency_key text not null, created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,import_row_id) references import_rows(organization_id,id), foreign key(organization_id,servant_id) references servants(organization_id,id));
create table import_action_receipts (id text primary key, organization_id text not null, actor_id text not null, import_row_id text not null, idempotency_key text not null, payload_hash text not null check(length(payload_hash)=64), created_at text not null, unique(organization_id,actor_id,idempotency_key), foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,import_row_id) references import_rows(organization_id,id));
create table import_batch_summaries (batch_id text primary key, organization_id text not null, summary_json jsonb not null, retained_until text not null, created_at text not null, updated_at text not null, foreign key(organization_id,batch_id) references import_batches(organization_id,id));

create table telegram_activation_codes (id text primary key, organization_id text not null, servant_id text not null, code_hash text not null check(length(code_hash)=64), expires_at text not null, attempts integer not null default 0 check(attempts between 0 and 5), consumed_at text, created_by text not null, created_at text not null, foreign key(organization_id,servant_id) references servants(organization_id,id), foreign key(organization_id,created_by) references users(organization_id,id), unique(organization_id,id));
create unique index telegram_activation_active on telegram_activation_codes(organization_id,servant_id) where consumed_at is null;
create table telegram_callback_grants (id text primary key, organization_id text not null, servant_id text not null, assignment_id text not null, action text not null check(action in ('accept','unavailable')), nonce_hash text not null check(length(nonce_hash)=64), expires_at text not null, consumed_at text, created_at text not null, foreign key(organization_id,servant_id) references servants(organization_id,id), foreign key(organization_id,assignment_id) references assignments(organization_id,id), unique(organization_id,nonce_hash), unique(organization_id,id));
create table telegram_notification_intents (id text primary key, organization_id text not null, servant_id text not null, assignment_id text, event_type text not null check(event_type in ('assignment_confirmation','assignment_reminder','critical_reminder')), idempotency_key text not null, due_at text not null, status text not null default 'pending' check(status in ('pending','sending','accepted_by_api','failed','cancelled')), attempt_count integer not null default 0 check(attempt_count between 0 and 3), last_error_category text, payload_json jsonb not null, created_at text not null, updated_at text not null, foreign key(organization_id,servant_id) references servants(organization_id,id), foreign key(organization_id,assignment_id) references assignments(organization_id,id), unique(organization_id,idempotency_key));
create table telegram_webhook_updates (organization_id text not null, update_id text not null, received_at text not null, primary key(organization_id,update_id));
create table telegram_emergency_reports (id text primary key, organization_id text not null, assignment_id text not null, servant_id text not null, status text not null default 'open' check(status in ('open','closed')), created_at text not null, foreign key(organization_id,assignment_id) references assignments(organization_id,id), foreign key(organization_id,servant_id) references servants(organization_id,id));
create unique index telegram_emergency_one_open on telegram_emergency_reports(organization_id,assignment_id) where status='open';
create table telegram_callback_receipts (id text primary key, organization_id text not null, callback_grant_id text not null, assignment_id text not null, expected_version integer not null, actual_version integer not null, actor_matches boolean not null check(actor_matches), state_matches boolean not null check(state_matches), created_at text not null, check(expected_version=actual_version), foreign key(organization_id,callback_grant_id) references telegram_callback_grants(organization_id,id), foreign key(organization_id,assignment_id) references assignments(organization_id,id), unique(organization_id,callback_grant_id));
create table telegram_activation_attempts (organization_id text not null, telegram_user_id text not null, window_started_at text not null, attempt_count integer not null check(attempt_count between 1 and 5), updated_at text not null, primary key(organization_id,telegram_user_id));
create table telegram_activation_requests (id text primary key, organization_id text not null, actor_id text not null, servant_id text not null, activation_id text not null, idempotency_key text not null, created_at text not null, foreign key(organization_id,actor_id) references users(organization_id,id), foreign key(organization_id,servant_id) references servants(organization_id,id), foreign key(organization_id,activation_id) references telegram_activation_codes(organization_id,id), unique(organization_id,actor_id,idempotency_key));
create table replacement_cases (id text primary key, organization_id text not null, service_id text not null, assignment_id text not null, service_role_id text not null, status text not null default 'open' check(status in ('open','resolved','escalated_manual','cancelled')), urgency text not null default 'standard' check(urgency in ('standard','critical')), reason text not null, resolved_assignment_id text, resolved_by text, resolved_at text, created_by text, created_at text not null, updated_at text not null, foreign key(organization_id,service_id) references worship_services(organization_id,id), foreign key(organization_id,assignment_id) references assignments(organization_id,id), foreign key(organization_id,service_role_id) references service_roles(organization_id,id), foreign key(organization_id,resolved_assignment_id) references assignments(organization_id,id), foreign key(organization_id,resolved_by) references users(organization_id,id), foreign key(organization_id,created_by) references users(organization_id,id), unique(organization_id,id));
create unique index replacement_cases_one_open on replacement_cases(organization_id, assignment_id) where status='open';
create index replacement_cases_lookup on replacement_cases(organization_id, status, urgency, created_at);
create index replacement_cases_service on replacement_cases(organization_id, service_id, status);
create table replacement_resolutions (id text primary key, organization_id text not null, case_id text not null, actor_id text not null, idempotency_key text not null, payload_hash text not null check(length(payload_hash)=64), created_at text not null, foreign key(organization_id,case_id) references replacement_cases(organization_id,id), foreign key(organization_id,actor_id) references users(organization_id,id), unique(organization_id,actor_id,idempotency_key));
create table attendance_records (id text primary key, organization_id text not null, service_id text not null, assignment_id text not null, servant_id text not null, status text not null check(status in ('present','late','absent','replaced')), checkin_time text, notes text, recorded_by text not null, created_at text not null, updated_at text not null, foreign key(organization_id,service_id) references worship_services(organization_id,id), foreign key(organization_id,assignment_id) references assignments(organization_id,id), foreign key(organization_id,servant_id) references servants(organization_id,id), foreign key(organization_id,recorded_by) references users(organization_id,id), unique(organization_id,assignment_id), unique(organization_id,id));
create index attendance_records_service on attendance_records(organization_id, service_id, status);
create index attendance_records_servant on attendance_records(organization_id, servant_id, status);
create table service_notes (id text primary key, organization_id text not null, service_id text, servant_id text, category text not null check(category in ('operational','subject_visible','restricted')), title text not null, content text not null, created_by text not null, created_at text not null, updated_at text not null, foreign key(organization_id,service_id) references worship_services(organization_id,id), foreign key(organization_id,servant_id) references servants(organization_id,id), foreign key(organization_id,created_by) references users(organization_id,id), unique(organization_id,id));
create index service_notes_category on service_notes(organization_id, category, created_at);
create index service_notes_service on service_notes(organization_id, service_id);
create index service_notes_servant on service_notes(organization_id, servant_id);
create table service_notes_acl (id text primary key, organization_id text not null, note_id text not null, user_id text not null, granted_by text not null, created_at text not null, foreign key(organization_id,note_id) references service_notes(organization_id,id) on delete cascade, foreign key(organization_id,user_id) references users(organization_id,id), foreign key(organization_id,granted_by) references users(organization_id,id), unique(organization_id,note_id,user_id));

insert into roles(id,code,name) values ('super_admin','super_admin','Super Admin'),('admin','admin','Admin/Sekretariat'),('worship_coordinator','worship_coordinator','Koordinator Ibadah'),('field_coordinator','field_coordinator','Koordinator Bidang'),('servant','servant','Pelayan'),('public_viewer','public_viewer','Jemaat/publik (nonaktif)');
insert into permissions(id,code,description) values ('user.read','user.read','Membaca identitas sesuai scope'),('user.manage_role','user.manage_role','Mengelola role pengguna'),('organization.read','organization.read','Membaca organisasi sesuai scope'),('organization.update','organization.update','Memperbarui organisasi'),('audit.read','audit.read','Membaca audit sesuai kebijakan'),('service.create_update','service.create_update','Membuat atau memperbarui ibadah'),('service.publish','service.publish','Menerbitkan ibadah'),('service.change_status','service.change_status','Mengubah status ibadah'),('assignment.read','assignment.read','Membaca penugasan sesuai scope'),('assignment.create_update','assignment.create_update','Membuat atau memperbarui penugasan'),('assignment.respond','assignment.respond','Merespons penugasan sendiri'),('servant.read','servant.read','Membaca profil pelayan sesuai scope'),('servant.create_update','servant.create_update','Membuat atau memperbarui profil pelayan'),('servant.manage_capability','servant.manage_capability','Mengelola capability pelayan'),('import.schedule','import.schedule','Mengimpor jadwal awal dari XLSX'),('incident.read_manage','incident.read_manage','Membaca dan mengelola insiden pelayanan'),('replacement.manage','replacement.manage','Mengelola alur dan pengesahan pengganti'),('attendance.record','attendance.record','Mencatat kehadiran dan check-in penugasan ibadah'),('notes.manage','notes.manage','Membuat dan mengelola catatan pelayanan serta evaluasi'),('reports.read','reports.read','Membaca rekapitulasi, analitik, dan laporan kinerja pelayanan'),('reports.export','reports.export','Mengekspor laporan data pelayanan ke format CSV');
insert into role_permissions select 'super_admin',id from permissions;
insert into role_permissions values ('admin','user.read'),('admin','organization.read'),('admin','audit.read'),('admin','service.create_update'),('admin','service.publish'),('admin','service.change_status'),('admin','assignment.read'),('admin','assignment.create_update'),('admin','servant.read'),('admin','servant.create_update'),('admin','servant.manage_capability'),('admin','import.schedule'),('admin','incident.read_manage'),('admin','replacement.manage'),('admin','attendance.record'),('admin','notes.manage'),('admin','reports.read'),('admin','reports.export'),('worship_coordinator','user.read'),('worship_coordinator','organization.read'),('worship_coordinator','service.create_update'),('worship_coordinator','service.publish'),('worship_coordinator','service.change_status'),('worship_coordinator','assignment.read'),('worship_coordinator','assignment.create_update'),('worship_coordinator','servant.read'),('worship_coordinator','servant.manage_capability'),('worship_coordinator','incident.read_manage'),('worship_coordinator','replacement.manage'),('worship_coordinator','attendance.record'),('worship_coordinator','notes.manage'),('worship_coordinator','reports.read'),('worship_coordinator','reports.export'),('field_coordinator','user.read'),('field_coordinator','organization.read'),('field_coordinator','assignment.read'),('field_coordinator','assignment.create_update'),('field_coordinator','servant.read'),('field_coordinator','servant.manage_capability'),('field_coordinator','incident.read_manage'),('field_coordinator','replacement.manage'),('field_coordinator','attendance.record'),('field_coordinator','notes.manage'),('field_coordinator','reports.read'),('field_coordinator','reports.export'),('servant','user.read'),('servant','assignment.read'),('servant','assignment.respond'),('servant','servant.read'),('servant','servant.create_update'),('servant','incident.read_manage'),('servant','replacement.manage'),('servant','reports.read');

create function spi_audit_immutable() returns trigger language plpgsql as $$ begin raise exception 'Audit is append only'; end $$;
create trigger audit_no_update before update on audit_logs for each row execute function spi_audit_immutable();
create trigger audit_no_delete before delete on audit_logs for each row execute function spi_audit_immutable();
create function spi_user_role_guard() returns trigger language plpgsql as $$ begin if new.role_id='public_viewer' then raise exception 'Public access disabled for MVP'; end if; return new; end $$;
create trigger no_public_role before insert or update of role_id on user_roles for each row execute function spi_user_role_guard();
create function spi_status_transition_guard() returns trigger language plpgsql as $$ begin if exists(select 1 from users where organization_id=new.organization_id and id=new.user_id and status=new.requested_status) then raise exception 'Account status transition must change status'; end if; return new; end $$;
create trigger account_status_requires_transition before insert on account_status_changes for each row execute function spi_status_transition_guard();
create function spi_retention_org_guard() returns trigger language plpgsql as $$ begin if not exists(select 1 from audit_logs where id=new.audit_log_id and organization_id=new.organization_id) then raise exception 'Retention hold audit organization mismatch'; end if; return new; end $$;
create trigger retention_hold_same_organization before insert or update of audit_log_id,organization_id on audit_retention_holds for each row execute function spi_retention_org_guard();
create function spi_capability_guard() returns trigger language plpgsql as $$ begin if new.status='active' and not exists(select 1 from capability_approvers where organization_id=new.organization_id and service_role_id=new.service_role_id and user_id=new.approved_by and active=1) then raise exception 'Capability approver not designated'; end if; return new; end $$;
create trigger capability_active_requires_approver before insert or update of status,approved_by,service_role_id,organization_id on servant_capabilities for each row execute function spi_capability_guard();
create function spi_scope_guard() returns trigger language plpgsql as $$ begin if (new.scope_type='service' and not exists(select 1 from worship_services where organization_id=new.organization_id and id=new.scope_id)) or (new.scope_type='field' and not exists(select 1 from service_fields where organization_id=new.organization_id and id=new.scope_id)) then raise exception 'Coordinator scope target mismatch'; end if; return new; end $$;
create trigger coordinator_scope_target before insert or update of organization_id,scope_type,scope_id on coordinator_scopes for each row execute function spi_scope_guard();
create function spi_assignment_guard() returns trigger language plpgsql as $$ declare assignment_count integer; assignment_limit integer; proposed_month text; begin if new.status in ('cancelled','reassigned') then return new; end if; if not exists(select 1 from servants where organization_id=new.organization_id and id=new.servant_id and status='active') then raise exception 'Assignment servant inactive'; end if; if not exists(select 1 from servant_capabilities where organization_id=new.organization_id and servant_id=new.servant_id and service_role_id=new.service_role_id and status='active') then raise exception 'Assignment capability unapproved'; end if; if exists(select 1 from availability_blocks b join worship_services s on s.organization_id=new.organization_id and s.id=new.worship_service_id where b.organization_id=new.organization_id and b.servant_id=new.servant_id and b.block_type='unavailable' and b.starts_at<s.ends_at and b.ends_at>s.starts_at) then raise exception 'Assignment availability conflict'; end if; select monthly_assignment_limit into assignment_limit from servant_capabilities where organization_id=new.organization_id and servant_id=new.servant_id and service_role_id=new.service_role_id; if assignment_limit is not null then select substr(starts_at,1,7) into proposed_month from worship_services where organization_id=new.organization_id and id=new.worship_service_id; select count(*) into assignment_count from assignments a join worship_services s on s.organization_id=a.organization_id and s.id=a.worship_service_id where a.id<>new.id and a.organization_id=new.organization_id and a.servant_id=new.servant_id and a.service_role_id=new.service_role_id and a.status not in ('cancelled','reassigned') and substr(s.starts_at,1,7)=proposed_month; if assignment_count>=assignment_limit then raise exception 'Assignment monthly limit exceeded'; end if; end if; return new; end $$;
create trigger assignment_integrity before insert or update of status,servant_id,service_role_id,worship_service_id on assignments for each row execute function spi_assignment_guard();

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

commit;
